AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  sam-app

  Sample SAM Template for sam-app

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 900

Metadata:
  AWS::ServerlessRepo::Application:
    Name: fbAdsLibApp
    Description: Scrape Ads from FbAdsLib and do analysis
    Author: Shaw741
    SpdxLicenseId: Apache-2.0
    LicenseUrl: LICENSE.txt
    ReadmeUrl: README.md
    Labels: ["fbAdsLib"]
    HomePageUrl: https://github.com/Shaw741/FB-Adlib-Web-App
    SemanticVersion: 0.0.1
    SourceCodeUrl: https://github.com/Shaw741/FB-Adlib-Web-App

Resources:
  FbAdsLibPageScraperFunction:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
    Metadata:
      DockerTag: python3.x
      DockerContext: ./functions/page_scraper
      Dockerfile: Dockerfile

  ActiveProxyCheckerFunction:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
    Metadata:
      DockerTag: python3.x
      DockerContext: ./functions/active_proxy_checker
      Dockerfile: Dockerfile

  FbAdsLibAdScraperFunction:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
    Metadata:
      DockerTag: python3.x
      DockerContext: ./functions/ad_scraper
      Dockerfile: Dockerfile

  FbAdsLibDataCleanerFunction:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
    Metadata:
      DockerTag: python3.x
      DockerContext: ./functions/data_cleaner
      Dockerfile: Dockerfile

  FbAdsLibDataStoreFunction:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
    Metadata:
      DockerTag: python3.x
      DockerContext: ./functions/data_store
      Dockerfile: Dockerfile

  FbAdsLibsStateMachine:
    Type: AWS::Serverless::StateMachine
    Properties:
      DefinitionUri: statemachine/fbadslib_scraper.asl.json
      Role: arn:aws:iam::257097519918:role/StepFunctionsLambdaRole
      Type: STANDARD
